services:
  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper:latest
    command: ["/bin/bash", "-c", "/workspace/scripts/install-gpu-tools.sh && exec whisper --model small --language fr --onnxruntime"]
    volumes:
      - ./whisper-data:/data
      - ./scripts:/workspace/scripts      # <-- montage du script
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    ports:
      - 127.0.0.1:10300:10300
    deploy:
      resources:
        reservations:
          devices:
            - driver: "rocm"
              count: all
              capabilities: ["gpu"]

  piper:
    container_name: piper
    image: rhasspy/wyoming-piper:latest
    command: ["/bin/bash", "-c", "/workspace/scripts/install-gpu-tools.sh && exec piper --voice fr-siwis-medium --onnxruntime"]
    volumes:
      - ./piper-data:/data
      - ./scripts:/workspace/scripts      # <-- montage du script
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    ports:
      - 127.0.0.1:10200:10200
    deploy:
      resources:
        reservations:
          devices:
            - driver: "rocm"
              count: all
              capabilities: ["gpu"]

networks:
  default:
    driver: bridge
